version: '3.8'

services:
  mcp-server:
    build:
      context: ../mcp-server-poc
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=mcp_user
      - POSTGRES_PASSWORD=mcp_password
      - POSTGRES_DB=mcp_db
    volumes:
      - ../mcp-server-poc:/app
      - /app/node_modules
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=mcp_user
      - POSTGRES_PASSWORD=mcp_password
      - POSTGRES_DB=mcp_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
